name: Publish

on:
  push:
    branches:
      - master

jobs:
  latest_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Copy Repo Files
      uses: actions/checkout@master
    - name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        version: latest
    - name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}
    - name: Login
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_TOKEN }}
    - name: Build
      run: docker buildx build -t myoung34/fast-cli:latest --output "type=image,push=true" --platform linux/amd64,linux/arm/v7,linux/arm64 .
